name: Icemaker

on:
  push:
    branches: [master, ci]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/install@v0.1
        with:
          crate: rustup-toolchain-install-master
          version: latest
          use-tool-cache: true
      - name: install master toolchain
        run: rustup-toolchain-install-master -f -n master  -c rustc-dev llvm-tools rust-src clippy rust-analyzer
