name: Icemaker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/install@v0.1
        with:
          crate: rustup-toolchain-install-master
          version: latest
      - name: run RTIM
        run: rustup-toolchain-install-master
